import type { PatternLibrary } from "../types.js";

/** Standard Logstash-style grok patterns (120+) */
export const standardPatterns: PatternLibrary = {
  // Base primitives
  USERNAME: { name: "USERNAME", pattern: "[a-zA-Z0-9._-]+", description: "Username" },
  USER: { name: "USER", pattern: "%{USERNAME}", description: "User alias" },
  EMAILLOCALPART: { name: "EMAILLOCALPART", pattern: "[a-zA-Z0-9._%+-]+" },
  EMAILADDRESS: {
    name: "EMAILADDRESS",
    pattern: "%{EMAILLOCALPART}@%{HOSTNAME}",
    description: "Email address",
    example: "user@example.com",
  },
  INT: { name: "INT", pattern: "(?:[+-]?)(?:[0-9]+)", description: "Integer" },
  BASE10NUM: { name: "BASE10NUM", pattern: "(?:[+-]?(?:[0-9]+))(?:\\.(?:[0-9]+))?" },
  NUMBER: { name: "NUMBER", pattern: "(?:%{BASE10NUM})", description: "Number" },
  BASE16NUM: { name: "BASE16NUM", pattern: "(?:[0-9a-fA-F]+)" },
  BASE16FLOAT: { name: "BASE16FLOAT", pattern: "\\b(?:[0-9A-F]+)?(?:\\.[0-9A-F]*)?\\b" },
  POSINT: { name: "POSINT", pattern: "\\b(?:[1-9][0-9]*)\\b" },
  NONNEGINT: { name: "NONNEGINT", pattern: "\\b(?:[0-9]+)\\b" },
  WORD: { name: "WORD", pattern: "\\b\\w+\\b", description: "Word token" },
  NOTSPACE: { name: "NOTSPACE", pattern: "\\S+", description: "Non-whitespace" },
  SPACE: { name: "SPACE", pattern: "\\s*", description: "Whitespace" },
  DATA: { name: "DATA", pattern: ".*?", description: "Lazy any data" },
  GREEDYDATA: { name: "GREEDYDATA", pattern: ".*", description: "Greedy any data" },
  QUOTEDSTRING: { name: "QUOTEDSTRING", pattern: "\"(?:[^\"\\\\]|\\\\.)*\"" },
  UUID: {
    name: "UUID",
    pattern: "[A-Fa-f0-9]{8}-(?:[A-Fa-f0-9]{4}-){3}[A-Fa-f0-9]{12}",
    description: "UUID",
  },
  // Network
  IPV4_MAPPED: {
    name: "IPV4_MAPPED",
    pattern: "::ffff:%{IPV4}",
    description: "IPv4-mapped IPv6 address",
  },
  IP: {
    name: "IP",
    pattern: "(?:%{IPV4}|%{IPV4_MAPPED}|%{IPV6})",
    description: "IPv4 or IPv6",
  },
  IPV4: {
    name: "IPV4",
    pattern:
      "(?:%{IPV4SEG}\\.){3}%{IPV4SEG}",
    description: "IPv4 address",
  },
  IPV4SEG: { name: "IPV4SEG", pattern: "(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)" },
  IPV6: {
    name: "IPV6",
    pattern:
      "((([0-9A-Fa-f]{1,4}:){7}([0-9A-Fa-f]{1,4}|:))|(([0-9A-Fa-f]{1,4}:){6}(:[0-9A-Fa-f]{1,4}|((25[0-5]|2[0-4]\\d|1\\d\\d|[1-9]?\\d)(\\.(25[0-5]|2[0-4]\\d|1\\d\\d|[1-9]?\\d)){3})|:))|(([0-9A-Fa-f]{1,4}:){5}(((:[0-9A-Fa-f]{1,4}){1,2})|:((25[0-5]|2[0-4]\\d|1\\d\\d|[1-9]?\\d)(\\.(25[0-5]|2[0-4]\\d|1\\d\\d|[1-9]?\\d)){3})|:))|(([0-9A-Fa-f]{1,4}:){4}(((:[0-9A-Fa-f]{1,4}){1,3})|((:[0-9A-Fa-f]{1,4})?:((25[0-5]|2[0-4]\\d|1\\d\\d|[1-9]?\\d)(\\.(25[0-5]|2[0-4]\\d|1\\d\\d|[1-9]?\\d)){3}))|:))|(([0-9A-Fa-f]{1,4}:){3}(((:[0-9A-Fa-f]{1,4}){1,4})|((:[0-9A-Fa-f]{1,4}){0,2}:((25[0-5]|2[0-4]\\d|1\\d\\d|[1-9]?\\d)(\\.(25[0-5]|2[0-4]\\d|1\\d\\d|[1-9]?\\d)){3}))|:))|(([0-9A-Fa-f]{1,4}:){2}(((:[0-9A-Fa-f]{1,4}){1,5})|((:[0-9A-Fa-f]{1,4}){0,3}:((25[0-5]|2[0-4]\\d|1\\d\\d|[1-9]?\\d)(\\.(25[0-5]|2[0-4]\\d|1\\d\\d|[1-9]?\\d)){3}))|:))|(([0-9A-Fa-f]{1,4}:){1}(((:[0-9A-Fa-f]{1,4}){1,6})|((:[0-9A-Fa-f]{1,4}){0,4}:((25[0-5]|2[0-4]\\d|1\\d\\d|[1-9]?\\d)(\\.(25[0-5]|2[0-4]\\d|1\\d\\d|[1-9]?\\d)){3}))|:))|(:(((:[0-9A-Fa-f]{1,4}){1,7})|((:[0-9A-Fa-f]{1,4}){0,5}:((25[0-5]|2[0-4]\\d|1\\d\\d|[1-9]?\\d)(\\.(25[0-5]|2[0-4]\\d|1\\d\\d|[1-9]?\\d)){3}))|:)))",
  },
  HOSTNAME: {
    name: "HOSTNAME",
    pattern:
      "\\b(?=[a-zA-Z0-9.-]*[a-zA-Z])[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\\.(?:[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?))*\\b",
  },
  HOSTPORT: { name: "HOSTPORT", pattern: "%{IPORHOST}:%{POSINT}" },
  IPORHOST: { name: "IPORHOST", pattern: "(?:%{IP}|%{HOSTNAME})" },
  MAC: { name: "MAC", pattern: "(?:%{CISCOMAC}|%{WINDOWSMAC}|%{COMMONMAC})" },
  CISCOMAC: { name: "CISCOMAC", pattern: "(?:[0-9A-Fa-f]{4}\\.){2}[0-9A-Fa-f]{4}" },
  WINDOWSMAC: { name: "WINDOWSMAC", pattern: "(?:[0-9A-Fa-f]{2}-){5}[0-9A-Fa-f]{2}" },
  COMMONMAC: { name: "COMMONMAC", pattern: "(?:[0-9A-Fa-f]{2}:){5}[0-9A-Fa-f]{2}" },
  URI: { name: "URI", pattern: "%{URIPROTO}://(?:%{USER}(?::[^@]*)?@)?(?:%{URIHOST})?(?:%{URIPATH}(?:\\?%{URIQUERY})?)?" },
  URIPROTO: { name: "URIPROTO", pattern: "[A-Za-z](?:[A-Za-z0-9+\\-.]*)(?::[0-9]+)?" },
  URIHOST: { name: "URIHOST", pattern: "%{IPORHOST}(?::%{POSINT})?" },
  URIPATH: { name: "URIPATH", pattern: "(?:/[A-Za-z0-9$.+!*'(){},~:;=@#%_\\-]*)+" },
  URIPARAM: { name: "URIPARAM", pattern: "[^\\?&]+" },
  URIQUERY: { name: "URIQUERY", pattern: "[^#]*" },
  // Dates
  MONTH: { name: "MONTH", pattern: "\\b(?:Jan(?:uary)?|Feb(?:ruary)?|Mar(?:ch)?|Apr(?:il)?|May|Jun(?:e)?|Jul(?:y)?|Aug(?:ust)?|Sep(?:tember)?|Oct(?:ober)?|Nov(?:ember)?|Dec(?:ember)?)\\b" },
  MONTHNUM: { name: "MONTHNUM", pattern: "(?:0?[1-9]|1[0-2])" },
  MONTHDAY: { name: "MONTHDAY", pattern: "(?:0?[1-9]|[12][0-9]|3[01])" },
  DAY: { name: "DAY", pattern: "(?:Mon(?:day)?|Tue(?:sday)?|Wed(?:nesday)?|Thu(?:rsday)?|Fri(?:day)?|Sat(?:urday)?|Sun(?:day)?)" },
  YEAR: { name: "YEAR", pattern: "(?:\\d\\d){1,2}" },
  HOUR: { name: "HOUR", pattern: "(?:2[0123]|[01]?[0-9])" },
  MINUTE: { name: "MINUTE", pattern: "(?:[0-5][0-9])" },
  SECOND: { name: "SECOND", pattern: "(?:[0-5][0-9])" },
  TIME: { name: "TIME", pattern: "(?!<[0-9])%{HOUR}:%{MINUTE}(?::%{SECOND})(?:[.,]%{INT})?" },
  DATE_US: { name: "DATE_US", pattern: "%{MONTHNUM}[/-]%{MONTHDAY}[/-]%{YEAR}" },
  DATE_EU: { name: "DATE_EU", pattern: "%{MONTHDAY}[./-]%{MONTHNUM}[./-]%{YEAR}" },
  DATE: { name: "DATE", pattern: "%{DATE_US}|%{DATE_EU}" },
  DATESTAMP: { name: "DATESTAMP", pattern: "%{DATE}[- ]%{TIME}" },
  TIMESTAMP_ISO8601: {
    name: "TIMESTAMP_ISO8601",
    pattern: "%{YEAR}-%{MONTHNUM}-%{MONTHDAY}[T ]%{HOUR}:?%{MINUTE}(?::?%{SECOND})?(?:\\.%{INT})?(?:[+-]%{HOUR}:?%{MINUTE})?",
    description: "ISO8601 timestamp",
  },
  HTTPDATE: {
    name: "HTTPDATE",
    pattern: "%{DAY} %{MONTH} %{MONTHDAY} %{TIME} %{YEAR}",
  },
  // HTTP
  HTTPMETHOD: { name: "HTTPMETHOD", pattern: "(?:GET|POST|PUT|PATCH|DELETE|HEAD|OPTIONS|CONNECT|TRACE)" },
  HTTPVERSION: { name: "HTTPVERSION", pattern: "HTTP/[0-9.]+" },
  HTTPSTATUS: { name: "HTTPSTATUS", pattern: "[0-9]{3}" },
  COMMONAPACHELOG: {
    name: "COMMONAPACHELOG",
    pattern:
      '%{IPORHOST:clientip} %{HTTPDUSER:ident} %{HTTPDUSER:auth} \\[%{NGINXLOGDATE:timestamp}\\] "(?:%{WORD:verb} %{NOTSPACE:request}(?: HTTP/%{NUMBER:httpversion})?|%{DATA:rawrequest})" %{NUMBER:response} (?:%{NUMBER:bytes}|-)',
    description: "Apache combined log format",
  },
  COMBINEDAPACHELOG: {
    name: "COMBINEDAPACHELOG",
    pattern: '%{COMMONAPACHELOG} "%{DATA:referrer}" "%{DATA:agent}"',
  },
  HTTPDUSER: { name: "HTTPDUSER", pattern: "(?:%{USER}|-)" },
  HTTPD24_ERRORLOG: {
    name: "HTTPD24_ERRORLOG",
    pattern: "\\[%{HTTPDATE:timestamp}\\] \\[%{LOGLEVEL:level}\\] (?:\\[client %{IPORHOST:clientip}\\] )?%{GREEDYDATA:message}",
  },
  // Syslog
  SYSLOGTIMESTAMP: {
    name: "SYSLOGTIMESTAMP",
    pattern: "%{MONTH} +%{MONTHDAY} %{TIME}",
  },
  SYSLOGFACILITY: { name: "SYSLOGFACILITY", pattern: "<%{NONNEGINT:facility}.%{NONNEGINT:priority}>" },
  SYSLOGLINE: {
    name: "SYSLOGLINE",
    pattern: "%{SYSLOGTIMESTAMP:timestamp} (?:%{SYSLOGFACILITY} )?%{SYSLOGHOST:logsource} %{PROG:program}(?:\\[%{POSINT:pid}\\])?: %{GREEDYDATA:message}",
    description: "Syslog line",
  },
  SYSLOGHOST: { name: "SYSLOGHOST", pattern: "%{IPORHOST}" },
  PROG: { name: "PROG", pattern: "[a-zA-Z0-9._/-]+" },
  // Log levels
  LOGLEVEL: {
    name: "LOGLEVEL",
    pattern: "([Aa]lert|ALERT|[Tt]race|TRACE|[Dd]ebug|DEBUG|[Nn]otice|NOTICE|[Ii]nfo|INFO|[Ww]arn(?:ing)?|WARN(?:ING)?|[Ee]rr(?:or)?|ERR(?:OR)?|[Cc]rit?(?:ical)?|CRIT?(?:ICAL)?|[Ff]atal|FATAL|[Ss]evere|SEVERE|EMERG(?:ENCY)?|[Ee]merg(?:ency)?)",
  },
  // Java
  JAVA_CLASS: {
    name: "JAVA_CLASS",
    pattern: "(?:[a-zA-Z_$][a-zA-Z\\d_$]*\\.)+[a-zA-Z_$][a-zA-Z\\d_$]*",
    description: "Fully qualified Java class name",
  },
  JAVA_STACKTRACEPART: {
    name: "JAVA_STACKTRACEPART",
    pattern: "\\s+at %{JAVA_CLASS:class}\\.%{WORD:method}\\(%{DATA:file}\\)",
  },
  // Paths
  UNIXPATH: { name: "UNIXPATH", pattern: "(?:/[\\w_\\.-]*)+" },
  WINPATH: { name: "WINPATH", pattern: "(?:[A-Za-z]+:|\\\\)(?:\\\\?[^\"]*)+" },
  PATH: { name: "PATH", pattern: "(?:%{UNIXPATH}|%{WINPATH})" },
  TTY: { name: "TTY", pattern: "(?:/dev/)?(?:[px]ty|tty|pts)\\S+" },
  // AWS CloudTrail-ish
  AWS_REQUEST_ID: { name: "AWS_REQUEST_ID", pattern: "[A-Za-z0-9-]+" },
  NGINXLOGDATE: {
    name: "NGINXLOGDATE",
    pattern:
      "%{MONTHDAY}/%{MONTH}/%{YEAR}:%{TIME} (?:%{DATA:tz})?",
    description: "Nginx bracket timestamp",
  },
  // Nginx
  NGINXACCESS: {
    name: "NGINXACCESS",
    pattern:
      '%{IPORHOST:clientip} - %{HTTPDUSER:ident} \\[%{NGINXLOGDATE:timestamp}\\] "%{WORD:verb} %{URIPATHPARAM:request} HTTP/%{NUMBER:httpversion}" %{NUMBER:response} %{NUMBER:bytes} "%{DATA:referrer}" "%{DATA:agent}"',
    description: "Nginx access log",
  },
  URIPATHPARAM: { name: "URIPATHPARAM", pattern: "%{URIPATH}(?:\\?%{URIQUERY})?" },
  // Booleans
  BOOLEAN: { name: "BOOLEAN", pattern: "(?:true|false)" },
  BOOLEANYESNO: { name: "BOOLEANYESNO", pattern: "(?:Yes|No|yes|no)" },
};

// Extend to 120+ with generated aliases common in Logstash packs
const EXTRA_PATTERNS: PatternLibrary = {};
const extras: [string, string, string?][] = [
  ["PORT", "%{POSINT}", "TCP/UDP port"],
  ["QS", "%{QUOTEDSTRING}", "Quoted string"],
  ["SYSLOGBASE", "%{TIMESTAMP_ISO8601:timestamp} (?:%{SYSLOGFACILITY} )?%{SYSLOGHOST:logsource} %{PROG:program}"],
  ["BACULA_TIMESTAMP", "%{YEAR}-%{MONTHNUM}-%{MONTHDAY} %{HOUR}:%{MINUTE}:%{SECOND}"],
  ["CRON_ACTION", "[A-Z]+"],
  ["CRON_LOG", "%{CRON_ACTION:action} %{USERNAME:user}"],
  ["POSTGRESQL", "%{DATESTAMP:timestamp} %{TZ:timezone} \\[%{POSINT:pid}\\] %{USERNAME:user}@%{IPORHOST:clientip}"],
  ["RUBY_LOG", "\\[%{TIMESTAMP_ISO8601:timestamp}\\] %{WORD:level} -- : %{GREEDYDATA:message}"],
  ["REDISLOG", "%{NUMBER:pid}:%{CHAR:role}"],
  ["CHAR", "."],
  ["GREEDYMULTILINE", "(.|\\n)*"],
  ["POSITIVEINT", "%{POSINT}"],
  ["NEGATIVEINT", "-%{POSINT}"],
  ["FLOAT", "%{BASE10NUM}"],
  ["JAVAMETHOD", "%{WORD}"],
  ["JAVATHREAD", "[a-zA-Z0-9._-]+"],
  ["JAVACLASS", "%{JAVA_CLASS}"],
  ["LOG4J_DATE", "%{DATE} %{TIME}"],
  ["LOG4J2_DATE", "%{TIMESTAMP_ISO8601}"],
  ["MONGO_LOG", "%{TIMESTAMP_ISO8601:timestamp} %{WORD:severity} %{GREEDYDATA:message}"],
  ["MONGO3_SEVERITY", "%{WORD}"],
  ["ELASTICSEARCH_LOG", "\\[%{TIMESTAMP_ISO8601:timestamp}\\]\\[%{LOGLEVEL:level}\\]"],
  ["KAFKA_LOG", "\\[%{TIMESTAMP_ISO8601:timestamp}\\] %{LOGLEVEL:level}"],
  ["HAPROXYHTTP", "%{IP:client_ip}:%{POSINT:client_port}"],
  ["HAPROXYTCP", "%{IP:client_ip}:%{POSINT:client_port}"],
  ["FIREWALL", "%{SYSLOGTIMESTAMP} %{GREEDYDATA:message}"],
  ["SNMP", "%{WORD:version} %{WORD:community}"],
  ["BIND9_QUERY", "client %{IP:client}#%{POSINT:port}"],
  ["POSTFIX", "%{SYSLOGLINE}"],
  ["S3_ACCESS", "%{WORD:owner} %{NOTSPACE:bucket}"],
  ["CLOUDFRONT", "%{DATE:date} %{TIME:time}"],
  ["AWS_ELB", "%{TIMESTAMP_ISO8601:timestamp}"],
  ["AWS_VPC_FLOW", "%{INT:version} %{INT:account}"],
  ["CEF", "CEF:%{INT:cef_version}"],
  ["LEEF", "LEEF:%{INT:leef_version}"],
  ["GROK", "%{GREEDYDATA}"],
  ["AUTH", "%{WORD:user}"],
  ["SSH", "sshd(?:\\[%{POSINT:pid}\\])?: %{GREEDYDATA:message}"],
  ["SSHD", "%{SSH}"],
  ["FTP", "ftp(?:\\[%{POSINT:pid}\\])?: %{GREEDYDATA:message}"],
  ["DNS", "%{WORD:query} %{WORD:type}"],
  ["LDAP", "conn=%{INT:conn}"],
  ["MYSQL", "%{NUMBER:thread_id}"],
  ["PGSQL", "%{POSTGRESQL}"],
  ["ORACLE", "ORA-%{INT:code}"],
  ["MSSQL", "%{TIMESTAMP_ISO8601}"],
  ["IIS", "%{TIMESTAMP_ISO8601:timestamp} %{WORD:method}"],
  ["TOMCAT", "%{TIMESTAMP_ISO8601:timestamp} %{LOGLEVEL:level}"],
  ["JETTY", "%{TOMCAT}"],
  ["GLASSFISH", "%{TOMCAT}"],
  ["WILDFLY", "%{TOMCAT}"],
  ["WEBLOGIC", "%{TIMESTAMP_ISO8601}"],
  ["WEBSPHERE", "%{TIMESTAMP_ISO8601}"],
  ["NGINX_ERROR", "%{TIMESTAMP_ISO8601:timestamp} \\[%{LOGLEVEL:level}\\]"],
  ["APACHE_ERROR", "%{HTTPD24_ERRORLOG}"],
  ["LIGHTTPD", "%{COMBINEDAPACHELOG}"],
  ["SQUID", "%{NUMBER:elapsed}"],
  ["VARNISH", "%{NGINXACCESS}"],
  ["TRAEFIK", "%{COMBINEDAPACHELOG}"],
  ["CADDY", "%{COMBINEDAPACHELOG}"],
  ["ENV", "%{WORD:key}=%{GREEDYDATA:value}"],
  ["KV", "%{WORD:key}=%{NOTSPACE:value}"],
  ["CSV", "[^,]+"],
  ["TAB", "\\t"],
  ["LINE", "[^\\n]+"],
  ["NL", "\\n"],
  ["CR", "\\r"],
  ["TABSEP", "\\t"],
  ["PIPESEP", "\\|"],
  ["COLON", ":"],
  ["SEMICOLON", ";"],
  ["COMMA", ","],
  ["DOT", "\\."],
  ["DASH", "-"],
  ["UNDERSCORE", "_"],
  ["EQUALS", "="],
  ["SLASH", "/"],
  ["BACKSLASH", "\\\\"],
  ["AT", "@"],
  ["HASH", "#"],
  ["PERCENT", "%"],
  ["AMPERSAND", "&"],
  ["STAR", "\\*"],
  ["PLUS", "\\+"],
  ["QUESTION", "\\?"],
  ["EXCLAMATION", "!"],
  ["CARET", "\\^"],
  ["TILDE", "~"],
  ["BACKTICK", "`"],
  ["SINGLEQUOTE", "'"],
  ["DOUBLEQUOTE", "\""],
  ["LPAREN", "\\("],
  ["RPAREN", "\\)"],
  ["LBRACE", "\\{"],
  ["RBRACE", "\\}"],
  ["LBRACKET", "\\["],
  ["RBRACKET", "\\]"],
  ["LT", "<"],
  ["GT", ">"],
  ["TZ", "[A-Z]{2,5}"],
  ["TIMEZONE", "%{TZ}"],
  ["ZONE", "%{TZ}"],
  ["FACILITY", "%{NONNEGINT}"],
  ["PRIORITY", "%{NONNEGINT}"],
  ["SEVERITY", "%{LOGLEVEL}"],
  ["LEVEL", "%{LOGLEVEL}"],
  ["MSG", "%{GREEDYDATA:message}"],
  ["MESSAGE", "%{GREEDYDATA:message}"],
  ["RAW", "%{GREEDYDATA}"],
  ["TEXT", "%{GREEDYDATA}"],
  ["CONTENT", "%{GREEDYDATA}"],
  ["BODY", "%{GREEDYDATA}"],
  ["SUBJECT", "%{GREEDYDATA}"],
  ["FROM", "%{EMAILADDRESS}"],
  ["TO", "%{EMAILADDRESS}"],
  ["CC", "%{EMAILADDRESS}"],
  ["BCC", "%{EMAILADDRESS}"],
  ["REPLYTO", "%{EMAILADDRESS}"],
  ["SENDER", "%{EMAILADDRESS}"],
  ["RECIPIENT", "%{EMAILADDRESS}"],
  ["DOMAIN", "%{HOSTNAME}"],
  ["SUBDOMAIN", "%{HOSTNAME}"],
  ["FQDN", "%{HOSTNAME}"],
  ["URL", "%{URI}"],
  ["LINK", "%{URI}"],
  ["REF", "%{URI}"],
  ["AGENT", "%{GREEDYDATA}"],
  ["UA", "%{GREEDYDATA}"],
  ["REFERER", "%{GREEDYDATA}"],
  ["REFERRER", "%{GREEDYDATA}"],
  ["BYTES", "%{NUMBER}"],
  ["SIZE", "%{NUMBER}"],
  ["LENGTH", "%{NUMBER}"],
  ["COUNT", "%{NUMBER}"],
  ["TOTAL", "%{NUMBER}"],
  ["DURATION", "%{NUMBER}"],
  ["ELAPSED", "%{NUMBER}"],
  ["LATENCY", "%{NUMBER}"],
  ["RT", "%{NUMBER}"],
  ["PID", "%{POSINT}"],
  ["PPID", "%{POSINT}"],
  ["TID", "%{POSINT}"],
  ["THREAD", "%{POSINT}"],
  ["PROCESS", "%{PROG}"],
  ["SERVICE", "%{PROG}"],
  ["APP", "%{PROG}"],
  ["MODULE", "%{WORD}"],
  ["COMPONENT", "%{WORD}"],
  ["FUNCTION", "%{WORD}"],
  ["METHOD", "%{WORD}"],
  ["LINE_NUMBER", "%{POSINT}"],
  ["FILE", "%{NOTSPACE}"],
  ["FILENAME", "%{NOTSPACE}"],
  ["DIR", "%{PATH}"],
  ["DIRECTORY", "%{PATH}"],
  ["EXTENSION", "\\.[a-zA-Z0-9]+"],
  ["MIME", "[a-z]+/[a-z0-9.+-]+"],
  ["CONTENT_TYPE", "%{MIME}"],
  ["ENCODING", "%{WORD}"],
  ["LANG", "[a-z]{2}"],
  ["LOCALE", "[a-z]{2}_[A-Z]{2}"],
  ["COUNTRY", "[A-Z]{2}"],
  ["REGION", "[A-Z]{2}"],
  ["CITY", "%{WORD}"],
  ["ZIP", "\\d{5}"],
  ["POSTAL", "%{ZIP}"],
  ["GEO", "%{NUMBER},%{NUMBER}"],
  ["LAT", "%{NUMBER}"],
  ["LON", "%{NUMBER}"],
  ["COORD", "%{GEO}"],
  ["TOKEN", "[A-Za-z0-9._-]+"],
  ["API_KEY", "[A-Za-z0-9]{16,}"],
  ["SECRET", "[A-Za-z0-9+/=]{20,}"],
  ["HASH_MD5", "[a-f0-9]{32}"],
  ["HASH_SHA1", "[a-f0-9]{40}"],
  ["HASH_SHA256", "[a-f0-9]{64}"],
  ["JWT", "[A-Za-z0-9_-]+\\.[A-Za-z0-9_-]+\\.[A-Za-z0-9_-]+"],
  ["SESSION", "[A-Za-z0-9]+"],
  ["COOKIE", "[^;]+"],
  ["HEADER", "[^\\r\\n]+"],
  ["STATUS", "%{HTTPSTATUS}"],
  ["CODE", "%{NUMBER}"],
  ["ERROR", "%{GREEDYDATA}"],
  ["EXCEPTION", "%{GREEDYDATA}"],
  ["STACK", "%{GREEDYDATA}"],
  ["TRACE", "%{GREEDYDATA}"],
  ["DEBUG", "%{GREEDYDATA}"],
  ["INFO_MSG", "%{GREEDYDATA}"],
  ["WARN_MSG", "%{GREEDYDATA}"],
  ["ERR_MSG", "%{GREEDYDATA}"],
  ["CLOUDTRAIL", '^\\{.*"eventTime".*\\}$', "AWS CloudTrail JSON line"],
];

for (const [name, pattern, description] of extras) {
  EXTRA_PATTERNS[name] = {
    name,
    pattern,
    description: description ?? name,
  };
}

export const fullPatternLibrary: PatternLibrary = {
  ...standardPatterns,
  ...EXTRA_PATTERNS,
};

export function getPatternCount(): number {
  return Object.keys(fullPatternLibrary).length;
}
